In [9]:
n=5
sum=0
for i in range(0,n+1):
    sum=sum+i
print(sum)

15


In [10]:
mean=sum/n
mean


3.0

In [14]:
n=6
odd=0
for i in range(1,n+1):
  if(i%2!=0):
      odd=odd+i
odd

9

In [15]:
n=100
sum=(n*(n+1))/2
print(sum)

5050.0


In [18]:
mat1=[[1,2,3,4,5],
    [7,8,9,10,11],
    [2,3,4,5,6],
    [6,7,8,9,10],
    [3,4,5,6,7]]
print(mat1)
mat2=[[1,2,3,4,5],
    [7,8,9,10,11],
    [2,3,4,5,6],
    [6,7,8,9,10],
    [3,4,5,6,7]]
print(mat2)

[[1, 2, 3, 4, 5], [7, 8, 9, 10, 11], [2, 3, 4, 5, 6], [6, 7, 8, 9, 10], [3, 4, 5, 6, 7]]
[[1, 2, 3, 4, 5], [7, 8, 9, 10, 11], [2, 3, 4, 5, 6], [6, 7, 8, 9, 10], [3, 4, 5, 6, 7]]


In [20]:
import numpy as np
mat1=np.array([[1,2,3,4,5],
    [7,8,9,10,11],
    [2,3,4,5,6],
    [6,7,8,9,10],
    [3,4,5,6,7]])
print(mat1)

[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [ 2  3  4  5  6]
 [ 6  7  8  9 10]
 [ 3  4  5  6  7]]


In [21]:
len(mat1[1,1:3])

2

In [25]:
#even no
for i in range(len(mat1[:,1])):
    for j in range(len(mat1[1,:])):
        if mat1[i,j]%2==0:
            mat1[i,j]=mat1[i,j]
        else:
            mat1[i,j]=0
print(mat1)

[[ 0  2  0  4  0]
 [ 0  8  0 10  0]
 [ 2  0  4  0  6]
 [ 6  0  8  0 10]
 [ 0  4  0  6  0]]


In [23]:
mat1[1,1]

8

In [35]:
#odd no
mat1=np.array([[1,2,3,4,5],
    [7,8,9,10,11],
    [2,3,4,5,6],
    [6,7,8,9,10],
    [3,4,5,6,7]])

for i in range(len(mat1[:,1])):
    for j in range(len(mat1[1,:])):
        if mat1[i,j]%2!=0:
            mat1[i,j]=mat1[i,j]
        else:
            mat1[i,j]=0
print(mat1)

[[ 1  0  3  0  5]
 [ 7  0  9  0 11]
 [ 0  3  0  5  0]
 [ 0  7  0  9  0]
 [ 3  0  5  0  7]]


In [34]:
import numpy as np
mat1=np.array([[1,2,3,4,5],
    [7,8,9,10,11],
    [2,3,4,5,6],
    [6,7,8,9,10],
    [3,4,5,6,7]])
for i in range(len(mat1[:,1])):
    for j in range(len(mat1[1,:])):
        if i==j:
            mat1[i,j]=mat1[i,j]
        else:
            mat1[i,j]=0
print(mat1)

[[1 0 0 0 0]
 [0 8 0 0 0]
 [0 0 4 0 0]
 [0 0 0 9 0]
 [0 0 0 0 7]]


In [51]:
import numpy as np
mat1=np.array([[1,2,3,4,5],
    [7,8,9,10,11],
    [2,3,4,5,6],
    [6,7,8,9,10],
    [3,4,5,6,7]])
for i in range(len(mat1[:,-1])):
    for j in range(len(mat1[1,:])):
         if i==j:
            mat1[i,j]=mat1[i,j]
         else:
            mat1[i,j]=0
print(mat1)

[[1 0 0 0 0]
 [0 8 0 0 0]
 [0 0 4 0 0]
 [0 0 0 9 0]
 [0 0 0 0 7]]


In [53]:
a=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
median=len(a)/2
print(median) 

7.5


In [63]:
import numpy as np
a=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
sum=0
for i in range(0,15):
    sum=sum+a[i]
    mean=sum/len(a)
    var=(a[i]-mean)**2/len(a)
    std=np.sqrt(var)
print(mean)
print(std)
print(var)

8.0
1.8073922282301278
3.2666666666666666
